### ISSUE TITLE
Check if phone contact is registered in database

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#27] opened 2018-12-20 19:11 UTC
I have added a new contact in my phone and the email of that contact is a registered user in the remote database but when it's loaded in contact list fragment there's an invite button beside it and I can't start to chat with that contact. How I start the chat with this contact? 
Also, there's a feature in Web app that user can find other users by querying their email like 'email:bob@example.com'. How can this feature be achieved in android application?

**Comment by or-else** [comment] 2018-12-21 06:13
Yes, it's a known issue. I'll fix it next.

**Comment by mohgh** [comment] 2018-12-21 09:14
Is SyncAdapter responsible for syncing phone contacts with remote? There's a line in `onPerfromSync` that program gets stuck on it.
`tinode.subscribe(Tinode.TOPIC_FND, null, null).waitResult();`
I manually run the code from account menu of my phone.

**Comment by or-else** [comment] 2018-12-21 09:57
Not just that. The list of credentials to search for is never updated. Even if the `waitResult` gets unstuck, the new contact will not be found.

**Comment by or-else** [comment] 2018-12-22 11:21
I added synchronization of contacts with the server. It works as expected now. Your new contact should appear without the [Invite] button now. 
I was unable to reproduce "There's a line in onPerfromSync that program gets stuck on it". Please let me know how to reproduce it.

The change in https://github.com/tinode/tindroid/tree/devel is dependent on a reciprocal change in the server (just for efficiency). So, either check out devel server too or just wait until I'll release 0.15.11-rc3 docker later today or tomorrow.

**Comment by mohgh** [comment] 2018-12-22 19:46
Thank you very much. I think my server was down at that moment. I'll pull from devel branch and test the result and let you know.

**Comment by or-else** [comment] 2018-12-23 07:11
I tested some more with server off and otherwise failing. I still cannot reproduce the sync service getting stuck. Maybe it's fixed now too.

**Comment by mohgh** [comment] 2018-12-23 20:07
Sorry if it's unrelated to this issue, but how can I upgrade the remote database version without removing its data?

**Comment by or-else** [comment] 2018-12-24 06:33
There is no way yet to upgrade the DB between releases. That's why it's still pre- version 1.

Maybe I can help you though. What database do you want to upgrade and form what version?

**Comment by mohgh** [comment] 2018-12-24 07:20
As you said in order to use the latest application I have to upgrade the server too. My last version was 105 and now I want to use 106.

**Comment by or-else** [comment] 2018-12-24 07:33
MySQL or RethinkDB?

**Comment by mohgh** [comment] 2018-12-24 07:41
RethinkDB

**Comment by or-else** [comment] 2018-12-24 11:18
Here you go (don't forget to backup before running it):
```js
r.db("tinode").table("users").indexCreate("DeletedAt")

r.db("tinode").table("topics").indexCreate("Owner")

r.db("tinode")
  .table("subscriptions")
  .filter(r.js('(function(sub) { return (sub.ModeWant&sub.ModeWant&128) != 0; })'))
  .forEach(function(sub) {
    return r.table("topics").get(sub.getField("Topic")).update({"Owner2": sub.getField("User")})
  })

r.db("tinode").table("kvmeta").get("version").update({"value": 106})
```

**Comment by or-else** [comment] 2018-12-24 12:19
I made a small mistake in the script. I've just fixed it. If you have already run it, re-run the third query (the long one) again.

**Comment by or-else** [comment] 2018-12-25 06:49
The most likely reason is inconsistent server config: you turned off email validation but still have the email: as a restricted name space.

**Comment by mohgh** [comment] 2018-12-25 07:57
I have turned off email validation. You are saying that if email validation is turned off, I can't set email discovery tags?

**Comment by or-else** [comment] 2018-12-25 08:54
Yep. 

I just made a change which separates the restriction from the option being present:
https://github.com/tinode/chat/commit/5613cb3251ae9e667abd3fa9f9becf3f5a9b1e13

Meanwhile you can remove this restriction by removing the entire section `acc_validation.email` from your config file. You can also rename the `email` section in `acc_validation` section to something else, like `x-email`.

**Comment by mohgh** [comment] 2018-12-25 18:11
I did as you said but nothing has changed.

**Comment by or-else** [comment] 2018-12-25 18:40
I cannot reproduce. It works exactly as expected.

Android source:
```
     return tinode.createAccountBasic(
          login, password, true, new String[]{"test:wakawaka", "ooga-chaka"},
          new MetaSetDesc<VxCard,String>(vcard, null),
          Credential.append(null, new Credential("email", email)));
```
Logcat:
```
2018-12-25 21:34:38.984 13322-13378/co.tinode.tindroid D/Tinode: out: {"acc":{"cred":[{"meth":"email","val":"gene+jack@tinode.co"}],"desc":{"public":{"fn":"Jack The Sawer","photo":{}}},"id":"74421","login":true,"scheme":"basic","secret":"amFjazpqYWNrMTIz","tags":["test:wakawaka","ooga-chaka"],"user":"new"}}
2018-12-25 21:34:39.153 13322-13378/co.tinode.tindroid D/Tinode: in: {"ctrl":{"id":"74421","params":{"authlvl":"auth","cred":["email"],"desc":{"created":"2018-12-25T18:34:39.746Z","updated":"2018-12-25T18:34:39.746Z","defacs":{"auth":"JRWPA","anon":"N"},"public":{"fn":"Jack The Sawer","photo":{}}},"expires":"2019-01-08T18:34:39.895Z","token":"+gmMe+3lDJI/7TRcFAABAAAAi80ENKYCWT3RjBMpvKWU5P8MmfebQzSWMjGuN1JRD48=","user":"usr-gmMe-3lDJI"},"code":300,"text":"validate credentials","ts":"2018-12-25T18:34:39.734Z"}}
```

Server log:
```
2018/12/25 21:34:39 in: '{"acc":{"cred":[{"meth":"email","val":"gene+jack@tinode.co"}],"desc":{"public":{"fn":"Jack The Sawer","photo":{}}},"id":"74421","login":true,"scheme":"basic","secret":"amFjazpqYWNrMTIz","tags":["test:wakawaka","ooga-chaka"],"user":"new"}}' ip='127.0.0.1:64539' sid='vzAeoLW1fN8' uid=''
```

MySQL table:
```
mysql> select * from usertags order by id desc limit 4;
+----+--------------------+---------------------------+
| id | userid             | tag                       |
+----+--------------------+---------------------------+
| 24 | 551757828050653184 | email:gene+jack@tinode.co |
| 23 | 551757828050653184 | test:wakawaka             |
| 22 | 551757828050653184 | ooga-chaka                |
| 21 | 547238976004558848 | email:gene+a1@tinode.co   |
+----+--------------------+---------------------------+
4 rows in set (0.00 sec)
```

**Comment by mohgh** [comment] 2018-12-25 18:52
This is my logcat:
```
out: {"acc":{"cred":[{"meth":"email","val":"ali77@dhdh.co"}],"desc":{"public":{"fn":"jraurajraj","photo":{}}},"id":"119854","login":true,"scheme":"basic","secret":"YWxpNzc6MTIzNDU2","tags":["email:ali77@dhdh.co"],"user":"new"}}
in: {"ctrl":{"id":"119854","params":{"authlvl":"auth","desc":{"created":"2018-12-25T18:44:39.95Z","updated":"2018-12-25T18:44:39.95Z","defacs":{"auth":"JRWPA","anon":"N"},"public":{"fn":"jraurajraj","photo":{}}},"expires":"2019-01-08T18:44:40.218Z","token":"ZTDh3yVAUqiY7zRcFAABAAEA6NxN7Fi2Aor8rxShL0IeceKOHcSpeeXfvEGndf6TTFo=","user":"usrZTDh3yVAUqg"},"code":200,"text":"ok","ts":"2018-12-25T18:44:39.948Z"}}
```
This is my server log:
```
in: '{"acc":{"cred":[{"meth":"email","val":"ali77@dhdh.co"}],"desc":{"public":{"fn":"jraurajraj","photo":{}}},"id":"119854","login":true,"scheme":"basic","secret":"YWxpNzc6MTIzNDU2","tags":["email:ali77@dhdh.co"],"user":"new"}}' ip='83.123.45.132:16859' sid='p_zuZ3uoZ_o' uid=''
```

And this is the user obj in rethinkdb:
```

{
"Access": {
"Anon": 0 ,
"Auth": 31
} ,
"CreatedAt": Tue Dec 25 2018 18:44:39 GMT+00:00 ,
"Devices": {
"1dfef549d68f16ab": {
"DeviceId": "cSL7ygJDIOI:APA91bGWzkMoPorPxoKo9gZXjcn7q_0r8N3r8jVqW3B6NW30VOgCfHny7ms49HhuDIjSZUiJbKMFwSMIsnl4F_jS0qEvEuS8j_oWWN_gpWArD76m8LpMvCE1rQaH5vi2FzMevX5NbCaC" ,
"Lang":  "en_US" ,
"LastSeen": Tue Dec 25 2018 18:44:39 GMT+00:00 ,
"Platform":  "android"
}
} ,
"Id":  "ZTDh3yVAUqg" ,
"LastSeen": null ,
"Public": {
"fn":  "jraurajraj" ,
"photo": { }
} ,
"State": 0 ,
"Tags": [
"basic:ali77"
] ,
"UpdatedAt": Tue Dec 25 2018 18:44:40 GMT+00:00 ,
"UserAgent":  ""
}
```

**Comment by or-else** [comment] 2018-12-25 18:57
Investigating.

**Comment by or-else** [comment] 2018-12-25 19:10
It's a bug, tags are getting overwritten. It's night here. I'll fix it tomorrow.

**Comment by or-else** [comment] 2018-12-26 16:50
It's a bit more complex than I thought originally so it's taking a bit longer to fix.

**Comment by or-else** [comment] 2018-12-27 13:36
I release 0.15.11-rc4 with the fix, but it's not a great fix. It should let you move forward but more refactoring of mags management is needed.

**Comment by mohgh** [comment] 2018-12-28 10:30
The problem with tags is resolved. I've registered two accounts and both have email discovery tags in the database. I've logged in with one of them and put another account's email in my contacts. But in contacts list the invite button is there. I even go to phone account menu and manually sync tinode account but on the line `if (future.waitResult()) {` waitresult returned false.

**Comment by mohgh** [comment] 2018-12-28 10:34
Here is the application logcat:
out: {"sub":{"id":"104948","set":{"desc":{"private":"................ (all emails in phone)"}}}}
in: {"ctrl":{"id":"104948","topic":"fnd","params":{"acs":{"want":"JP","given":"JP","mode":"JP"}},"code":200,"text":"ok","ts":"2018-12-28T10:31:51.626Z"}}
out: {"get":{"id":"104949","sub":{},"topic":"fnd","what":"sub"}}
in: {"ctrl":{"id":"104949","topic":"fnd","params":null,"code":400,"text":"malformed","ts":"2018-12-28T10:31:51.731Z"}}

**Comment by mohgh** [comment] 2018-12-28 10:37
Server logs:
```
2018/12/28 05:31:26 in: '{"sub":{"get":{"desc":{"ims":"2018-12-28T09:57:06.662Z"},"what":"desc sub"},"id":"104947","topic":"me"}}' ip='151.239.211.224:18397' sid='TaxFgIof0-k' uid='S7OcnZSp8U4'
2018/12/28 05:31:26 hub: started usrS7OcnZSp8U4 created= false
2018/12/28 05:31:51 in: '{"sub":{"id":"104948","set":{"desc":{"private":"email:mehdi@zibatar.com,email:saskha90@gmail.com,email:mohammadpz@aut.ac.ir,email:kdowlati@gmail.com,email:mahin.motevali8189@gmail.com,email:max.c.lv@gmail.com,email:h_kouhi@yahoo.com,email:sasha@gmail.com,email:technicalenglish@chmail.com,email:fb.aerospace@yahoo.com,email:saeed.sa10572@gmail.com,email:saeedsa10572@gmail.com,email:vipdomain100@yahoo.com,email:majid.zare71@gmail.com,email:ehsan.e.71@chmail.ir,email:rafiei.mahdi@gmail.com,email:farzad.tondro@g<...>' ip='151.239.211.224:18397' sid='TaxFgIof0-k' uid='S7OcnZSp8U4'
2018/12/28 05:31:51 hub: started fndS7OcnZSp8U4 created= false
2018/12/28 05:31:51 in: '{"get":{"id":"104949","sub":{},"topic":"fnd","what":"sub"}}' ip='151.239.211.224:18397' sid='TaxFgIof0-k' uid='S7OcnZSp8U4'
2018/12/28 05:31:51 topic[fndS7OcnZSp8U4] meta.Get.Sub failed: malformed
```

**Comment by or-else** [comment] 2018-12-28 11:21
I see two problems:

1. Even if the sync is successful, `ContactListFragment` is not updated. It's something on the Android side that I'm missing. Once the app is restarted everything is fine. I can't find why ContactListFragment  is not updated after the sync. Maybe the adapter is not restarted or something like that.

2. In your log there is an error: 
`2018/12/28 05:31:51 topic[fndS7OcnZSp8U4] meta.Get.Sub failed: malformed` 
So the search for contacts fails and returns no results. The most likely reason is an unparseable search query. I added more debug logging. Maybe it will help in finding the exact reason why it fails. Or maybe you can send me the search string to gene@tinode.co and I'll try to reproduce.

P.S. You probably don't want to publish all those emails here.

**Comment by or-else** [comment] 2018-12-28 11:41
I've removed the emails from your comment.

**Comment by mohgh** [comment] 2018-12-28 12:03
Instead of the full list of contacts, I only send one contact (the one I'm looking for) and it worked as it should. I think the problem may be the length of the request because I have hundreds of numbers and emails on my phone.

**Comment by or-else** [comment] 2018-12-28 12:11
I thought about length but it should not be. Even if it's truncated somewhere it will just lose those contacts at the end. It will not reject the query itself

**Comment by mohgh** [comment] 2018-12-28 12:11
Maybe somewhere the messages are clipped if there are longer than a threshold and the json format is gets malformed. In the logcat the `out: {"sub":{"id":"66323","set":{"desc":{"private":".............` log is malform.

**Comment by or-else** [comment] 2018-12-28 12:13
The server-side log trims the messages just to make logs more readable, but the message itself is OK otherwise it would drop the message alltogether.

**Comment by or-else** [comment] 2018-12-28 12:15
is it possible that your list has substrings like `,,` or `"`?

**Comment by mohgh** [comment] 2018-12-28 12:41
I should manually sync from account menu of the phone in order to all new contact getting synced.

**Comment by or-else** [comment] 2018-12-28 13:15
I just pushed two changes.  I think both issues are fixed now. Please try.

8a0967b make sure query is valid in case of empty contacts
d6c4d24 restart loader instead of init - otherwise contacts don't refresh

**Comment by or-else** [comment] 2018-12-28 13:22
> How often is the syncing procedure getting executed?

`requestSync` is called on successful login, then Android OS decides when to sync automatically.

**Comment by mohgh** [comment] 2018-12-28 14:00
Let's say I create a contact in my phone and then I enter the application. Shouldn't my contact list include this new contact if it's present in the remote database? This isn't the current behavior of the app now.

**Comment by or-else** [comment] 2018-12-28 14:11
You are saying `requestSync` should be called in `onResume` in `ContactsActivity`?

**Comment by or-else** [comment] 2018-12-28 14:14
Calling on every onResume is going to generate a lot of traffic for the user.

**Comment by mohgh** [comment] 2018-12-28 14:15
Maybe keep track of synced contacts in the local db and if there's a new contact, check if it's a tinode user.

**Comment by mohgh** [comment] 2018-12-28 14:16
There's another issue that an existing contact became a tinode user.

**Comment by or-else** [comment] 2018-12-28 14:18
> Maybe keep track of synced contacts in the local db and if there's a new contact

I don't see an obvious way to keep track of contacts. The Android Contacts DB does not have a usable timestamp of contact creation. The columns like `CONTACT_STATUS_TIMESTAMP` are updated every time the person is contacted.

**Comment by or-else** [comment] 2018-12-28 14:19
> There's another issue that an existing contact became a tinode user.

The the user status will automatically update at the next sync.

**Comment by or-else** [comment] 2018-12-28 14:20
> Maybe keep track of synced contacts in the local db and if there's a new contact

One way to do it is to run a ContentObserver service to monitor changes to contacts.

**Comment by mohgh** [comment] 2018-12-28 16:54
I put a call to `requestSync` in splash activity.

**Comment by or-else** [comment] 2018-12-28 17:02
A better place would be somewhere here: https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/UiUtils.java#L328

Otherwise it will try to login twice.

**Comment by mohgh** [comment] 2018-12-28 19:18
What does this log mean:
`in: {"ctrl":{"id":"104032","topic":"fnd","code":304,"text":"already subscribed","ts":"2001-03-28T19:15:06.564Z"}}`
I get this and one new email contact does not get synced. But when I uninstall the app and then install it again this new contact got synced too.

**Comment by mohgh** [comment] 2018-12-28 20:21
here is logcat on syncing.
```
out: {"sub":{"id":"83460","set":{"desc":{"private":".......all contacts......
in: {"ctrl":{"id":"83460","topic":"fnd","code":304,"text":"already subscribed","ts":"2001-03-28T20:20:06.112Z"}}
out: {"get":{"id":"83461","sub":{"ims":"2001-03-28T17:04:39.535Z"},"topic":"fnd","what":"sub"}}
in: {"meta":{"id":"83461","topic":"fnd","ts":"2001-03-28T20:20:06.197Z","sub":[{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"user":"usr2PrTGj-zQ9g"}]}}
```

**Comment by mohgh** [comment] 2018-12-28 21:49
I dig deeper and understand the reason it failed to sync contacts. On fresh install the server responds with this:
```
{"meta":{"id":"95750","topic":"fnd","ts":"2001-03-28T21:35:52.671Z","sub":[{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"public":{"fn":"----user namr-----","photo":{}},"private":["email:-----user email-------"],"user":"usr2PrTGj-zQ9g"},{"updated":"2001-03-15T15:34:34.625Z","acs":{"mode":"JRWPA"},"public":{"fn":"102"},"private":["email:---user email-----"],"user":"usrLcJXw7jVKvs"}]}}
```
But after first time, all other calls even it has new users, the server reponse is this:
```
{"meta":{"id":"95754","topic":"fnd","ts":"2001-03-28T21:43:38.436Z","sub":[{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"user":"usr2PrTGj-zQ9g"},{"updated":"2001-03-15T15:34:34.625Z","acs":{"mode":"JRWPA"},"user":"usrLcJXw7jVKvs"}]}}
```
As you can see the second time we don't have required data to update contacts list.

**Comment by or-else** [comment] 2018-12-29 08:09
> out: {"sub":{"id":"83460","set":{"desc":{"private":".......all contacts......
> in: {"ctrl":{"id":"83460","topic":"fnd","code":304,"text":"already subscribed","ts":"2001-03-28T20:20:06.112Z"}}

The 83460 request is ignored (`"code":304`), thus the list of emails you sent in `"private":"......` is ignored. It's ignored because the subscription to `fnd` is already established earlier. Do you know where you send the first `{sub: {topic: "fnd"...}` request? If you look at the logcat you should see it earlier in the log.

> I dug deeper and understand the reason it failed to sync contacts. On fresh install the server responds with this:

Yes, it is by design and it should not matter.

**Comment by mohgh** [comment] 2018-12-29 20:13
No, it's not fixed yet.
I've forced close the application and perform a manual sync. here's logcat:

```
out: {"hi":{"dev":"fePqNkC5sno:APA91bG2YxjDKbfxCx4PeYuHWfxFyt-s7xjP4dlPg6docRtpO18z4hYb-Hmkm1CF8YSS1OeNDZ2kamvoryHT4cHTaGFV829W2Mw0zrWuG8YA_jnQGdpzIjJOCuoEeU9gINxgaUbQokdh","id":"99647","lang":"en_US","ua":"Tindroid/0.15.6-47-ge52f311 (Android 8.0.0; en_US); noor/0.15","ver":"0.15"}}
in: {"ctrl":{"id":"99647","params":{"build":"rethinkdb:v0.15.11-rc4","ver":"0.15"},"code":201,"text":"created","ts":"2001-03-29T20:06:58.009Z"}}
out: {"login":{"id":"99648","scheme":"token","secret":"uYBdaRD9YIPHB9Y6FAABAAEARMN2r4m61LlHGzMDlGHTHXz8V8BJh3tFTGR4QXQBbeU="}}
in: {"ctrl":{"id":"99648","params":{"authlvl":"auth","expires":"2001-04-12T19:53:43.006Z","token":"uYBdaRD9YIPHB9Y6FAABAAEARMN2r4m61LlHGzMDlGHTHXz8V8BJh3tFTGR4QXQBbeU=","user":"usruYBdaRD9YIM"},"code":200,"text":"ok","ts":"2001-03-29T20:06:58.166Z"}}
out: {"sub":{"id":"99649","topic":"fnd"}}
in: {"ctrl":{"id":"99649","topic":"fnd","params":{"acs":{"want":"JP","given":"JP","mode":"JP"}},"code":200,"text":"ok","ts":"2001-03-29T20:06:58.241Z"}}
out: {"set":{"desc":{"private":------all emails--------------}}}
in: {"ctrl":{"id":"99650","topic":"fnd","code":200,"text":"ok","ts":"2001-03-29T20:07:00.287Z"}}
out: {"get":{"id":"99651","sub":{"ims":"2001-03-28T17:04:39.535Z"},"topic":"fnd","what":"sub"}}
in: {"meta":{"id":"99651","topic":"fnd","ts":"2001-03-29T20:07:00.477Z","sub":[{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"user":"usr2PrTGj-zQ9g"},{"updated":"2001-03-15T15:34:34.625Z","acs":{"mode":"JRWPA"},"user":"usrLcJXw7jVKvs"},{"updated":"2001-03-15T15:34:34.807Z","acs":{"mode":"JRWPA"},"user":"usrOaLTmFcavLI"},{"updated":"2001-03-15T15:34:35.009Z","acs":{"mode":"JRWPA"},"user":"usrUusAIbuvp6g"},{"updated":"2001-03-15T15:34:37.934Z","acs":{"mode":"JRWPA"},"user":"usrfgYmnBqcxbM"}]}}
```

**Comment by or-else** [comment] 2018-12-30 07:47
It's complete in a sense that all subscriptions should be present. The `public` and `private` are stripped but that should not affect the update. What's the uid of the new user? Do you see it in the array here?

[{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"user":"usr2PrTGj-zQ9g"},{"updated":"2001-03-15T15:34:34.625Z","acs":{"mode":"JRWPA"},"user":"usrLcJXw7jVKvs"},{"updated":"2001-03-15T15:34:34.807Z","acs":{"mode":"JRWPA"},"user":"usrOaLTmFcavLI"},{"updated":"2001-03-15T15:34:35.009Z","acs":{"mode":"JRWPA"},"user":"usrUusAIbuvp6g"},{"updated":"2001-03-15T15:34:37.934Z","acs":{"mode":"JRWPA"},"user":"usrfgYmnBqcxbM"}]

**Comment by or-else** [comment] 2018-12-30 08:59
Actually, I see why it does not work. Fixing it now.

**Comment by mohgh** [comment] 2018-12-30 09:12
> It's complete in a sense that all subscriptions should be present. The `public` and `private` are stripped but that should not affect the update. What's the uid of the new user? Do you see it in the array here?
> 
> [{"updated":"2001-03-28T17:04:39.535Z","acs":{"mode":"JRWPA"},"user":"usr2PrTGj-zQ9g"},{"updated":"2001-03-15T15:34:34.625Z","acs":{"mode":"JRWPA"},"user":"usrLcJXw7jVKvs"},{"updated":"2001-03-15T15:34:34.807Z","acs":{"mode":"JRWPA"},"user":"usrOaLTmFcavLI"},{"updated":"2001-03-15T15:34:35.009Z","acs":{"mode":"JRWPA"},"user":"usrUusAIbuvp6g"},{"updated":"2001-03-15T15:34:37.934Z","acs":{"mode":"JRWPA"},"user":"usrfgYmnBqcxbM"}]

The new user is present in here but because public and private fields are empty the contact in the phone will not get updated. You can see the logic in updateContact and addContact methods.

**Comment by or-else** [comment] 2018-12-30 15:43
Hopefully this will fix it: https://github.com/tinode/tindroid/commit/bd292ae376fd645dceacba8372f1c343a41af559

I also made a change on the server but that's probably unnecessary. I'll roll it back.

**Comment by mohgh** [comment] 2018-12-30 16:37
The issue is resolved. Thank you very much, sir.

**Closed** 2018-12-30 16:37 UTC
Labels: bug
