### ISSUE TITLE
when voice is too long, fragement will crash

### ISSUE THREAD

**Issue by robinfoxnan** [tinode/tindroid#139] opened 2022-12-17 14:44 UTC
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Describe the bug**

**To Reproduce**
1. Go to 'chat with somebody'
2. Click on 'button of mac phone'
3. Scroll down to 'speak for 5 or longer seconds'
4. See error: fragment will crash 

**Expected behavior**
sure, it should be sent to peer, 
but not

**Screenshots**

**Tindroid (please complete the following information):**
 - Version [0.20.9]

**Comment by or-else** [comment] 2022-12-17 16:19
There was a crash when **playing** a long audio recorded on Android https://github.com/tinode/tindroid/issues/137. It was fixed in https://github.com/tinode/tindroid/commit/d1abd6e6b4d769b21d31d922906e4cf97150dde9.

I cannot reproduce the crash with **recording**.

**Comment by robinfoxnan** [comment] 2022-12-18 05:40
en，yes,  it works wll in semulator, 
I see it on MIUI platform, 
I am using a phone of MI 11

**Comment by robinfoxnan** [comment] 2022-12-18 06:02
sometimes, when My figure left the autio button  the fragement sent nothing,
I can see this in emulator too

**Comment by or-else** [comment] 2022-12-18 15:59
If you are reporting a crash during **recording** (not playback), then I cannot reproduce. There is nothing in Crashlytics either. I need a way to reproduce the crash or a stacktrace.

**Comment by or-else** [comment] 2022-12-18 16:05
> the fragement sent nothing

The recording is discarded if it's too short.

**Comment by or-else** [comment] 2023-01-31 02:24
No update in five weeks. I assume it's been resolved.

**Closed by or-else** 2023-01-31 02:24 UTC
Labels: bug, cannot reproduce
