### ISSUE TITLE
Not focusing to conversation fragment from push notification.

### ISSUE THREAD

**Issue by trademkose** [tinode/tindroid#29] opened 2019-02-06 12:42 UTC
Hi,
Android app doesn't focus to related fragment of conversation when I click to New Message Push notification.

Best regards.

**Comment by or-else** [comment] 2019-02-06 14:48
I cannot reproduce. Please provide more information.

I just fixed an issue when the notification was missing altogether: https://github.com/tinode/tindroid/commit/40aeb2c7be7a0d8fc622fab12af684a9934c29d8. But that seems to be different from the issue you described.

**Comment by or-else** [comment] 2019-02-11 18:14
Any update on this?

**Comment by or-else** [comment] 2019-02-13 13:34
With help of @maksfreetimer I found a bug which may have caused this issue. It's been fixed on the server side.

**Comment by or-else** [comment] 2019-02-15 13:56
A possible fix has been released in https://github.com/tinode/chat/releases/tag/v0.15.13-rc2
If the problem remains, please open another issue and provide more details. Thanks.

**Closed by or-else** 2019-02-15 13:57 UTC
Labels: incomplete
