### ISSUE TITLE
Avatars do not work

### ISSUE THREAD

**Issue by piratov** [tinode/tindroid#128] opened 2022-08-25 13:55 UTC
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
https://groups.google.com/g/tinode/c/MIK7B0rrce0

**Describe the bug**
You cannot set an avatar and the ones already installed from the web client are not displayed. Not set per user, group, or channel.

**To Reproduce**
Use the possibilities that are available by installing an avatar in the android client.

**Expected behavior**
Set avatar for user, group and channel from camera or gallery mobile application.

**Screenshots**
ANDROID
<img src="https://user-images.githubusercontent.com/17856390/186680264-62d743e3-e072-402a-8130-3e110f254dbb.png" width="255"> <img src="https://user-images.githubusercontent.com/17856390/186680260-cb2ae707-e3bb-4104-a90e-fc33ebdbfda9.png" width="255">
WEB
<img src="https://user-images.githubusercontent.com/17856390/186682887-64880944-d267-431e-8f26-888a4e212de8.png" width="255"> <img src="https://user-images.githubusercontent.com/17856390/186683679-f51f4544-3a54-40a2-afbc-ea46ca0c9889.png" width="255">

**Tindroid (please complete the following information):**
 - Version [0.19 and 0.20 (https://github.com/tinode/tindroid/tree/next)]
 - Device [X30 Cubot]
 - Android API Version -

**Server**
- Type [api.tinode.co or your own setup]
- Server type [unmodified or customized]
- Server version [0.19, 0.20]

**Additional context**
[bugreport-X30_EEA-QP1A.190711.020-2022-08-25-15-44-19.zip](https://github.com/tinode/tindroid/files/9425143/bugreport-X30_EEA-QP1A.190711.020-2022-08-25-15-44-19.zip)

Console server
Opening tinode /#contacts with avatars.(android)
I2022/08/25 14:52:37 ws: session started _4KIaqdULl8 IP_ADDRESS:9441 2
I2022/08/25 14:52:37 in: '{"hi":{"dev":"clC3FqjmRIKRZkstmUxuIb:APA91bFMenksWZgfQ-mTjCuLOWqPveWnMCOKd6kkxOP-15xdD0xCSzQ41ZxO3i2yVp5lMy6vdABhIPfULEp8uNpdZlR9MMtYG5nMMJiYxiCjME3odGbIzuZjPN9U3gejkRKZ-WCv6q5g","id":"104062","lang":"ru_RU","ua":"Tindroid/20n (Android 10; ru_RU); tindroid/20n","ver":"0.20"}}' sid='_4KIaqdULl8' uid=''
I2022/08/25 14:52:37 in: '{"login":{"id":"104063","scheme":"token","secret":"2WYMJdwbHit41xljFAABAAEA8f228kenCSc5SwDLfEv+8UX71Np49Q3sapZQapx7Ftw="}}' sid='_4KIaqdULl8' uid=''
I2022/08/25 14:52:37 in: '{"sub":{"get":{"desc":{"ims":"2022-08-23T05:31:04.375Z"},"sub":{"ims":"2022-08-24T05:04:17.955Z"},"what":"desc sub tags cred","empty":false},"id":"104064","topic":"me"}}' sid='_4KIaqdULl8' uid='2WYMJdwbHis'
I2022/08/25 14:52:37 in: '{"sub":{"get":{"desc":{"ims":"2022-08-23T05:31:04.375Z"},"sub":{"ims":"2022-08-24T05:04:17.955Z"},"what":"desc sub tags cred","empty":false},"id":"104065","topic":"me"}}' sid='_4KIaqdULl8' uid='2WYMJdwbHis'
I2022/08/25 14:52:37 in: '{"sub":{"id":"104066","topic":"fnd"}}' sid='_4KIaqdULl8' uid='2WYMJdwbHis'
I2022/08/25 14:52:37 in: '{"get":{"id":"104067","sub":{"ims":"2022-08-25T11:52:25.005Z"},"topic":"fnd","what":"sub"}}' sid='_4KIaqdULl8' uid='2WYMJdwbHis'

As a comparison, open tinode /#contacts WEB client, where there are avatars.(web)
I2022/08/25 14:48:42 ws: session started kkpdTMKYC24 IP_ADDRESS:55275 1
I2022/08/25 14:48:42 in: '{"hi":{"id":"100998","ver":"0.20.0-rc1","ua":"TinodeWeb/0.20.0-rc1 (Chrome/97.0; Win32); tinodejs/0.20.0-rc1","lang":"en-US","platf":"web"}}' sid='kkpdTMKYC24' uid=''
I2022/08/25 14:48:42 in: '{"login":{"id":"100999","scheme":"token","secret":"2WYMJdwbHivf1RljFAABAAEA0O4v2Oqi5/AubsJoTMMcE7mtbYUenJiXJknw6zzGsog="}}' sid='kkpdTMKYC24' uid=''
I2022/08/25 14:48:42 in: '{"sub":{"id":"101000","topic":"me","get":{"what":"sub desc tags cred"}}}' sid='kkpdTMKYC24' uid='2WYMJdwbHis'
I2022/08/25 14:48:42 media serve: OK, uid= 2WYMJdwbHis
I2022/08/25 14:48:42 media serve: OK, uid= 2WYMJdwbHis

Attempting to set a gallery image or photo from the camera to an avatar.(android)
I2022/08/25 14:40:18 ws: session started WS2bnUp9BI4 IP_ADDRESS:9372 1
I2022/08/25 14:40:18 in: '{"hi":{"dev":"clC3FqjmRIKRZkstmUxuIb:APA91bFZX-_kS_bY_2YxkLtkziQn7Jxu3k6clg2vAy_1kfqhIqNUuxWkfzmdFR8DVFI7QDSEKmnhjHLpEgugw0Ljw0qyXlTg2z5fEmZ_fGsyV6XAPMF7Q6LwKnxgbkmm7m4cUq2BXsYK","id":"130423","lang":"ru_RU","ua":"Tindroid/20n (Android 10; ru_RU); tindroid/20n","ver":"0.20"}}' sid='WS2bnUp9BI4' uid=''
I2022/08/25 14:40:18 in: '{"login":{"id":"130424","scheme":"token","secret":"cxSpTP2DymeQ1BljFAABAAEAmaNwDr6Rpl0aKGVLmqgGKWE/IAao0owvQYqVKMkZ6Ts="}}' sid='WS2bnUp9BI4' uid=''
I2022/08/25 14:40:18 in: '{"sub":{"get":{"desc":{"ims":"2022-08-22T08:49:50.906Z"},"sub":{"ims":"2022-08-24T04:49:21.003Z"},"what":"desc sub tags cred","empty":false},"id":"130425","topic":"me"}}' sid='WS2bnUp9BI4' uid='cxSpTP2Dymc'
I2022/08/25 14:40:18 in: '{"sub":{"get":{"desc":{"ims":"2022-08-22T08:49:50.906Z"},"sub":{"ims":"2022-08-24T04:49:21.003Z"},"what":"desc sub tags cred","empty":false},"id":"130426","topic":"me"}}' sid='WS2bnUp9BI4' uid='cxSpTP2Dymc'
I2022/08/25 14:40:18 in: '{"sub":{"id":"130427","topic":"fnd"}}' sid='WS2bnUp9BI4' uid='cxSpTP2Dymc'
I2022/08/25 14:40:18 in: '{"get":{"id":"130428","sub":{"ims":"2022-08-25T11:40:00.404Z"},"topic":"fnd","what":"sub"}}' sid='WS2bnUp9BI4' uid='cxSpTP2Dymc'

A large image closes the application.(android)
Sometimes when trying to add or save an avatar, there is a message “Failed” (action_failed)

**Comment by or-else** [comment] 2022-08-25 18:06
Do I understand correctly that you are using your own server?

**Comment by or-else** [comment] 2022-08-25 18:08
Is this your own build of Android?

**Comment by or-else** [comment] 2022-08-25 18:09
Please attach **the original** file you use as avatar. First zip it then attach to be sure it's not scaled down by github.

**Comment by piratov** [comment] 2022-08-26 06:43
> Do I understand correctly that you are using your own server?

Yes, but the problem is common. It doesn't matter your own or downloaded github.


> > A large image closes the application.(android)
> 
> I don't see a crash report in Crashlytics. Is this your own build of Android?

I can repeat crash report on the downloaded github?


> Please attach **the original** file you use as avatar. First zip it then attach to be sure it's not scaled down by github.

If you are talking about the problem of crash due to a larger image? I think any image is larger than allowed on the server.


Additional Information..
It seems I'm starting to understand what the collision with the avatar is. If you change the avatar in android, then the avatar in the web client disappears. And vice versa, if you set an avatar in the web client, then the avatar in the android client disappears.
Try it you will see.

**Comment by piratov** [comment] 2022-08-27 09:37
To create a bugreport, I used the latest available versions
https://github.com/tinode/chat/tree/next
https://github.com/tinode/tindroid/tree/next

[bugreport-X30_EEA-QP1A.190711.020-2022-08-27-12-09-55.zip](https://github.com/tinode/tindroid/files/9437624/bugreport-X30_EEA-QP1A.190711.020-2022-08-27-12-09-55.zip)


Avatar I used
[Screenshot_20200502-193517.zip](https://github.com/tinode/tindroid/files/9437647/Screenshot_20200502-193517.zip)

**Comment by or-else** [comment] 2022-08-27 17:37
> I can repeat crash report on the downloaded github?

Maybe. Did you try? I don't need the crash itself, I need the step to reproduce it. I know the crash happens when you scale the image too much, I just can't reproduce it.

**Comment by piratov** [comment] 2022-08-27 19:41
> > I can repeat crash report on the downloaded github?
> 
> Maybe. Did you try? I don't need the crash itself, I need the step to reproduce it. I know the crash happens when you scale the image too much, I just can't reproduce it.

here is an example photo from the camera

[IMG_20220728_195342.zip](https://github.com/tinode/tindroid/files/9438564/IMG_20220728_195342.zip)
or
https://files.fm/u/zercugsfe

**Comment by or-else** [comment] 2022-08-27 20:28
Can you describe the steps to the crash?

**Comment by or-else** [comment] 2022-08-27 22:52
Never mind. I managed to reproduce the crash.

**Comment by piratov** [comment] 2022-08-27 23:06
Two videos one crash another avatar installation
https://files.fm/u/4tvu68m4w

**Comment by or-else** [comment] 2022-08-28 01:58
Crash fixed in https://github.com/tinode/tindroid/commit/f29f8412d0861622e08feba08be71dd89dead32c
Thanks.

**Comment by or-else** [comment] 2022-09-01 19:32
The broken avatars were due to a bug in webapp. I believe it's fixed now. Please double check.

**Comment by piratov** [comment] 2022-09-01 21:53
Unfortunately no change.

Additional difficulties have been added.
It is not immediately possible to connect (503) to the server. And also log in the first time (409).
When adding an avatar, the account is logged out.

**Comment by or-else** [comment] 2022-09-01 22:27
Did you update the server?

**Comment by piratov** [comment] 2022-09-01 22:31
> Did you update the server?

Yes, devel last

**Comment by or-else** [comment] 2022-09-01 22:39
Anyway, I cannot reproduce. Please show the logcat.

**Comment by piratov** [comment] 2022-09-01 23:16
https://files.fm/f/c7hwf5x7f
or
[logcat.txt](https://github.com/tinode/tindroid/files/9473872/logcat.txt)

**Comment by or-else** [comment] 2022-09-01 23:42
You are using an android client prior to https://github.com/tinode/tindroid/commit/f29f8412d0861622e08feba08be71dd89dead32c
Please use an updated client.

**Comment by piratov** [comment] 2022-09-02 00:02
> You are using an android client prior to [f29f841](https://github.com/tinode/tindroid/commit/f29f8412d0861622e08feba08be71dd89dead32c) Please use an updated client.

Yes, using last [e8a1294](https://github.com/tinode/tindroid/commit/e8a129428056c9064a711d47f3c45f401c6e295f)  No more this error [f29f841](https://github.com/tinode/tindroid/commit/f29f8412d0861622e08feba08be71dd89dead32c)

**Closed** 2022-11-04 21:40 UTC
Labels: bug

**Comment by piratov** [comment] 2022-11-20 11:24
I found out that without https, avatars will not be loaded. This is the main problem on client android

**Comment by or-else** [comment] 2022-11-20 15:17
If you found a bug, please file a bug report.
